language: clojure
jdk:
- oraclejdk8
env:
  global:
  - secure: SNzIZ0A3W3MH8dm4oB3Q8mQN8jhP8gIyW5gSwlU17Fbk2i23jyw38gfNZCtyZFvjTudeuQaWlxHpaftiUmN1luMVPc/8TUDpq3k3mbiishFQkMd6tHnhngPh3KhAVTv/Meno9i4fn9LegVU2xqiGJkFvnWHpsgsHbOEHrnYsl9o=
install: "./etc/travis-setup.sh"
script: lein test && lein invoke
after_script: heroku keys:remove $USER@`hostname`
